definitions:
  steps:
    - step: &build
        name: Install and Build
        image: node:16
        caches:
          - node
        script:
          - rm -rf .next
          - rm -rf .vscode
          - rm -rf .gitignore
          - rm -rf package-lock.json
          - rm -rf node_modules
          - rm -rf README.md
          - rm -rf out
          - npm install
          - npm run build
          - npm run export
          - ls out/
        artifacts:
          - out/**
    - step: &s3-upload
        name: Deploy to S3
        image: atlassian/pipelines-awscli
        script:
          - ls out/
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - aws s3 sync out/ s3://$AWS_BUCKET_NAME --acl public-read --delete

pipelines:
  branches:
    master:
      - step: *build
      - step:
          <<: *s3-upload
          deployment: Production
    # staging:
    #   - step: *build
    #   - step:
    #       <<: *s3-upload
    #       deployment: Staging
